### PR TITLE
Auto-accept remote deletes

### PR DESCRIPTION
**Pull request by magush27**
https://github.com/hyphacoop/distributed-press-organizing/issues/162

The code in apsystem.test doesn't work, what is the problem?

### CODE REVIEW

**Comment by akhileshthite** [comment]
> [hyphacoop/distributed-press-organizing#162](https://github.com/hyphacoop/distributed-press-organizing/issues/162)
> 
> The code in apsystem.test doesn't work, what is the problem?

I think it's because of the merge conflicts, can you resolve those?

**Comment by RangerMauve** [comment]
Yeah, please fix the conflict before we merge. Also, the CI is showing that apsystem.ts has unnecessary import for ActivityStore, please remove it so the linter can pass. You can also run the linter locally with `npm run lint`

https://github.com/hyphacoop/social.distributed.press/actions/runs/11520192999/job/32070934990

**Comment by fauno** [comment]
solved the conflict and linted!

**Comment by magush27** [comment]
> Tests seem to be failing 😅

Yep, I had this problem before when I made the first merge with main on the tests file and I don't know what is the problem. I've checked the code and I'm using the activity as other tests do and the correct endpoints (I think hehe), have you got any idea of what is going on?

**Comment by magush27** [comment]
> The issue was that the actor wasn't being mocked correctly.
> 
> Then there was an issue with the delete activity not being mocked by the mockFetch
> 
> Then there was an issue with the wrong activity ID being used in apsystem.ts. It was using the `id` of the Delete activity instead of the `object` the delete was pointing at
> 
> Then there was the unnecessary check that the inbox was being called at the end
> 
> Looks good to go now
> 
> Next time please try to get the tests passing before getting a review and if you're stuck writing down the steps you took to debug so far. 👍

Oh, I see. Thanks for the explanation and sorry! 
Next time I'll get the tests passing before making the pr

**Pull request merged**
